name: Tauri Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Tauri CLI
        run: npm install -g tauri

      - name: Build Tauri app
        run: tauri build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/bundle/**/*  # Adjust this path based on your build output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
